---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-app-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: backstage
            url: https://kubernetes.default.svc
            path1: manifests/backstage-manifests
  template:
    metadata:
      name: "{{cluster}}-application"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/VamsiKrishna082/gitops-bridge-infra.git
          targetRevision: main
          path: "{{path1}}"
          directory:
            recurse: true
            exclude: properties.yaml
      destination:
        server: "{{url}}"
        namespace: "backstage"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true