apiVersion: v1
kind: Secret
metadata:
  name: backstage-secret
  namespace: backstage
  annotations:
    cert-manager.io/cluster-issuer: backstage-issuer
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
